@ECHO off

:: EDIT these paths to your directories, respectively:

:: MaskRCNN folder (delete the word "rem" from the beginning of the line and set the path if you already have
:: a MaskRCNN folder - in this case, move the word "rem" from between the beginning of the last 2 lines):
set "pathToInsert=C:\\Users\\jaspe\\Downloads\\biomagdsb-master\\biomagdsb-master\\Mask_RCNN"

:: working directory where you downloaded the code and will have the output under ~\kaggle_workflow\outputs\maskrcnn:
set root_dir=C:\\Users\\jaspe\\Downloads\\biomagdsb-master\\biomagdsb-master

:: directory of your masks for style transfer learning input. Provide ONLY if you have custom masks for your input
:: images, otherwise the default folder will be the presegmented masks generated by our pipeline.
rem set images_dir="maskFolder"
:: -----------------------------------------------------------------------------


:: --- DO NOT EDIT from here ---
run_workflow_prepareStyle4singleExperiment.bat %root_dir% %images_dir%
run_workflow_prepareStyle4singleExperiment.bat %root_dir%